// <auto-generated />

using JetStoryAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace JetStoryAPI.Migrations
{
  [DbContext(typeof(StoryContext))]
  partial class StoryContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("JetStoryAPI.Models.Story", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd();

        b.Property<string>("Category");

        b.Property<string>("Content");

        b.Property<string>("Name");

        b.Property<int>("Time");

        b.Property<string>("publishedDate");

        b.Property<string>("writer");

        b.HasKey("Id");

        b.ToTable("Stories");
      });
#pragma warning restore 612, 618
    }
  }
}